var WIKI_SITES = [
	{
		name: "麻将维基",
		desc: "麻将维基",
		project_name: "麻将维基",
		url: "http://mahjong.huiji.wiki",
		page_url: "http://mahjong.huiji.wiki/wiki/",
		api_url: "http://mahjong.huiji.wiki/api.php",
	},
	{
		name: "逆境无赖维基",
		desc: "逆境无赖维基",
		project_name: "逆境无赖维基",
		url: "http://kaiji.huiji.wiki",
		page_url: "http://kaiji.huiji.wiki/wiki/",
		api_url: "http://kaiji.huiji.wiki/api.php",
	},
	{
		name: "魔戒中文维基",
		desc: "魔戒中文维基",
		project_name: "魔戒中文维基",
		url: "http://lotr.huiji.wiki",
		page_url: "http://lotr.huiji.wiki/wiki/",
		api_url: "http://lotr.huiji.wiki/api.php",
	},
	{
		name: "模板仓库",
		desc: "模板仓库",
		project_name: "模版仓库",
		url: "http://templatemanager.huiji.wiki",
		page_url: "http://templatemanager.huiji.wiki/wiki/",
		api_url: "http://templatemanager.huiji.wiki/api.php",
	},
	{
		name: "Wikimedia Commons",
		desc: "Wikimedia Commons",
		project_name: "Commons",
		url: "https://commons.wikimedia.org",
		page_url: "https://commons.wikimedia.org/wiki/",
		api_url: "https://commons.wikimedia.org/w/api.php",
	},
	{
		name: "SakiWiki",
		desc: "SakiWiki：《咲-Saki-》中文百科全书",
		project_name: "SakiWiki",
		url: "http://saki.cc",
		page_url: "http://saki.cc/",
		api_url: "http://saki.cc/api.php",
	},
	//		{
	//			name: "Tolkein Gateway",
	//			desc: "Tolkein Gateway",
	//			url: "http://www.tolkiengateway.net",
	//			page_url: "http://www.tolkiengateway.net/wiki/",
	//			api_url: "http://www.tolkiengateway.net/w/api.php",
	//		},
	//		{
	//			name: "日文维基百科",
	//			desc: "日文维基百科",
	//			url: "http://ja.wikipedia.org",
	//			page_url: "http://ja.wikipedia.org/wiki/",
	//			api_url: "http://ja.wikipedia.org/w/api.php",
	//		},
	//  {
	//    name : "",
	//    desc : "",
	//    url : "",
	//    page_url : "",
	//    api_url : "",
	//  },
];