var WIKI_SITES = [
	{
		name: "红铜智库中文维基",
		desc: "红铜智库中文维基",
		project_name: "红铜智库中文维基",
		url: "http://coppermind.huiji.wiki",
		page_url: "http://coppermind.huiji.wiki/wiki/",
		api_url: "http://coppermind.huiji.wiki/api.php",
	},
	{
		name: "小樱的封印之书",
		desc: "小樱的封印之书",
		project_name: "小樱的封印之书",
		url: "http://cardcaptorsakura.huiji.wiki",
		page_url: "http://cardcaptorsakura.huiji.wiki/wiki/",
		api_url: "http://cardcaptorsakura.huiji.wiki/api.php",
	},
	{
		name: "魔法门之英雄无敌3",
		desc: "魔法门之英雄无敌3",
		project_name: "魔法门之英雄无敌3",
		url: "http://hmm3.huiji.wiki",
		page_url: "http://hmm3.huiji.wiki/wiki/",
		api_url: "http://hmm3.huiji.wiki/api.php",
	},
	{
		name: "麻将维基",
		desc: "麻将维基",
		project_name: "麻将维基",
		url: "http://mahjong.huiji.wiki",
		page_url: "http://mahjong.huiji.wiki/wiki/",
		api_url: "http://mahjong.huiji.wiki/api.php",
	},
	{
		name: "逆境无赖维基",
		desc: "逆境无赖维基",
		project_name: "逆境无赖维基",
		url: "http://kaiji.huiji.wiki",
		page_url: "http://kaiji.huiji.wiki/wiki/",
		api_url: "http://kaiji.huiji.wiki/api.php",
	},
	{
		name: "魔戒中文维基",
		desc: "魔戒中文维基",
		project_name: "魔戒中文维基",
		url: "http://lotr.huiji.wiki",
		page_url: "http://lotr.huiji.wiki/wiki/",
		api_url: "http://lotr.huiji.wiki/api.php",
	},
	{
		name: "模板仓库",
		desc: "模板仓库",
		project_name: "模版仓库",
		url: "http://templatemanager.huiji.wiki",
		page_url: "http://templatemanager.huiji.wiki/wiki/",
		api_url: "http://templatemanager.huiji.wiki/api.php",
	},
	{
		name: "Wikimedia Commons",
		desc: "Wikimedia Commons",
		project_name: "Commons",
		url: "https://commons.wikimedia.org",
		page_url: "https://commons.wikimedia.org/wiki/",
		api_url: "https://commons.wikimedia.org/w/api.php",
	},
	{
		name: "SakiWiki",
		desc: "SakiWiki：《咲-Saki-》中文百科全书",
		project_name: "SakiWiki",
		url: "http://saki.cc",
		page_url: "http://saki.cc/",
		api_url: "http://saki.cc/api.php",
	},
	{
		name: "the Coppermind",
		desc: "the Coppermind",
		project_name: "Coppermind",
		url: "http://coppermind.net",
		page_url: "http://coppermind.net/wiki/",
		api_url: "http://coppermind.net/w/api.php",
	},
	{
		name: "Heroes of Might and Magic III wiki",
		desc: "Heroes of Might and Magic III wiki",
		project_name: "Heroes of Might and Magic III wiki",
		url: "http://heroes.thelazy.net",
		page_url: "http://heroes.thelazy.net/wiki/",
		api_url: "http://heroes.thelazy.net/wiki/api.php",
	},
	{
		name: "漫威电影宇宙资料站",
		desc: "漫威电影宇宙资料站",
		project_name: "漫威电影宇宙资料站",
		url: "http://mcu.huiji.wiki",
		page_url: "http://mcu.huiji.wiki/wiki/",
		api_url: "http://mcu.huiji.wiki/api.php",
	},
	{
		name: "Cardcaptor Sakura Wiki",
		desc: "Cardcaptor Sakura Wiki",
		project_name: "Cardcaptor Sakura Wiki",
		url: "http://ccs.wikia.com/",
		page_url: "http://ccs.wikia.com/wiki/",
		api_url: "http://ccs.wikia.com/api.php",
	},
	//		{
	//			name: "Tolkein Gateway",
	//			desc: "Tolkein Gateway",
	//			url: "http://www.tolkiengateway.net",
	//			page_url: "http://www.tolkiengateway.net/wiki/",
	//			api_url: "http://www.tolkiengateway.net/w/api.php",
	//		},
	//		{
	//			name: "日文维基百科",
	//			desc: "日文维基百科",
	//			url: "http://ja.wikipedia.org",
	//			page_url: "http://ja.wikipedia.org/wiki/",
	//			api_url: "http://ja.wikipedia.org/w/api.php",
	//		},
	//  {
	//    name : "",
	//    desc : "",
	//    url : "",
	//    page_url : "",
	//    api_url : "",
	//  },
];