var WIKI_SITES = [
	{
		name: "红铜智库中文维基",
		desc: "红铜智库中文维基",
		project_name: "红铜智库中文维基",
		url: "http://coppermind.huijiwiki.com",
		page_url: "http://coppermind.huijiwiki.com/wiki/",
		api_url: "http://coppermind.huijiwiki.com/api.php",
	},
	{
		name: "白箱中文维基",
		desc: "白箱中文维基",
		project_name: "白箱中文维基",
		url: "http://shirobako.huijiwiki.com",
		page_url: "http://shirobako.huijiwiki.com/wiki/",
		api_url: "http://shirobako.huijiwiki.com/api.php",
	},
	{
		name: "JoJo的奇妙冒险中文维基",
		desc: "JoJo的奇妙冒险中文维基",
		project_name: "JoJo的奇妙冒险中文维基",
		url: "http://jojo.huijiwiki.com",
		page_url: "http://jojo.huijiwiki.com/wiki/",
		api_url: "http://jojo.huijiwiki.com/api.php",
	},
	{
		name: "小樱的封印之书",
		desc: "小樱的封印之书",
		project_name: "小樱的封印之书",
		url: "http://cardcaptorsakura.huijiwiki.com",
		page_url: "http://cardcaptorsakura.huijiwiki.com/wiki/",
		api_url: "http://cardcaptorsakura.huijiwiki.com/api.php",
	},
	{
		name: "魔法门之英雄无敌3",
		desc: "魔法门之英雄无敌3",
		project_name: "魔法门之英雄无敌3",
		url: "http://hmm3.huijiwiki.com",
		page_url: "http://hmm3.huijiwiki.com/wiki/",
		api_url: "http://hmm3.huijiwiki.com/api.php",
	},
	{
		name: "麻将维基",
		desc: "麻将维基",
		project_name: "麻将维基",
		url: "http://mahjong.huijiwiki.com",
		page_url: "http://mahjong.huijiwiki.com/wiki/",
		api_url: "http://mahjong.huijiwiki.com/api.php",
	},
	{
		name: "逆境无赖维基",
		desc: "逆境无赖维基",
		project_name: "逆境无赖维基",
		url: "http://kaiji.huijiwiki.com",
		page_url: "http://kaiji.huijiwiki.com/wiki/",
		api_url: "http://kaiji.huijiwiki.com/api.php",
	},
	{
		name: "魔戒中文维基",
		desc: "魔戒中文维基",
		project_name: "魔戒中文维基",
		url: "http://lotr.huijiwiki.com",
		page_url: "http://lotr.huijiwiki.com/wiki/",
		api_url: "http://lotr.huijiwiki.com/api.php",
	},
	{
		name: "模板仓库",
		desc: "模板仓库",
		project_name: "模版仓库",
		url: "http://templatemanager.huijiwiki.com",
		page_url: "http://templatemanager.huijiwiki.com/wiki/",
		api_url: "http://templatemanager.huijiwiki.com/api.php",
	},
	{
		name: "Wikimedia Commons",
		desc: "Wikimedia Commons",
		project_name: "Commons",
		url: "https://commons.wikimedia.org",
		page_url: "https://commons.wikimedia.org/wiki/",
		api_url: "https://commons.wikimedia.org/w/api.php",
	},
	{
		name: "en.wikipedia",
		desc: "Wikipedia",
		project_name: "Wikipedia",
		url: "https://en.wikipedia.org",
		page_url: "https://en.wikipedia.org/wiki/",
		api_url: "https://en.wikipedia.org/w/api.php",
	},
	{
		name: "ja.wikipedia",
		desc: "Wikipedia",
		project_name: "Wikipedia",
		url: "https://ja.wikipedia.org",
		page_url: "https://ja.wikipedia.org/wiki/",
		api_url: "https://ja.wikipedia.org/w/api.php",
	},
	{
		name: "SakiWiki",
		desc: "SakiWiki：《咲-Saki-》中文百科全书",
		project_name: "SakiWiki",
		url: "http://saki.cc",
		page_url: "http://saki.cc/",
		api_url: "http://saki.cc/api.php",
	},
	{
		name: "the Coppermind",
		desc: "the Coppermind",
		project_name: "Coppermind",
		url: "http://coppermind.net",
		page_url: "http://coppermind.net/wiki/",
		api_url: "http://coppermind.net/w/api.php",
	},
	{
		name: "Heroes of Might and Magic III wiki",
		desc: "Heroes of Might and Magic III wiki",
		project_name: "Heroes of Might and Magic III wiki",
		url: "http://heroes.thelazy.net",
		page_url: "http://heroes.thelazy.net/wiki/",
		api_url: "http://heroes.thelazy.net/wiki/api.php",
	},
	{
		name: "漫威电影宇宙资料站",
		desc: "漫威电影宇宙资料站",
		project_name: "漫威电影宇宙资料站",
		url: "http://mcu.huijiwiki.com",
		page_url: "http://mcu.huijiwiki.com/wiki/",
		api_url: "http://mcu.huijiwiki.com/api.php",
	},
	{
		name: "冰与火之歌中文维基",
		desc: "冰与火之歌中文维基",
		project_name: "冰与火之歌中文维基",
		url: "http://asoiaf.huijiwiki.com",
		page_url: "http://asoiaf.huijiwiki.com/wiki/",
		api_url: "http://asoiaf.huijiwiki.com/api.php",
	},
	{
		name: "圣斗士星矢中文资料站",
		desc: "圣斗士星矢中文资料站",
		project_name: "圣斗士星矢中文资料站",
		url: "http://saintseiya.huijiwiki.com",
		page_url: "http://saintseiya.huijiwiki.com/wiki/",
		api_url: "http://saintseiya.huijiwiki.com/api.php",
	},
	{
		name: "Cardcaptor Sakura Wiki",
		desc: "Cardcaptor Sakura Wiki",
		project_name: "Cardcaptor Sakura Wiki",
		url: "http://ccs.wikia.com/",
		page_url: "http://ccs.wikia.com/wiki/",
		api_url: "http://ccs.wikia.com/api.php",
	},
	{
		name: "Seiyapedia",
		desc: "Seiyapedia",
		project_name: "Seiyapedia",
		url: "http://saintseiya.wikia.com/",
		page_url: "http://saintseiya.wikia.com/wiki/",
		api_url: "http://saintseiya.wikia.com/api.php",
	},
	{
		name: "es CCS Wiki",
		desc: "Sakura Card Captors Wiki",
		project_name: "Sakura Card Captors Wiki",
		url: "http://es.sakuracardcaptors.wikia.com/",
		page_url: "http://es.sakuracardcaptors.wikia.com/wiki/",
		api_url: "http://es.sakuracardcaptors.wikia.com/api.php",
	},
	{
		name: "jojo Wiki",
		desc: "JoJo's Bizarre Encyclopedia",
		project_name: "JoJo's Bizarre Encyclopedia",
		url: "http://jojo.wikia.com/",
		page_url: "http://jojo.wikia.com/wiki/",
		api_url: "http://jojo.wikia.com/api.php",
	},
	{
		name: "ja shirobako Wiki",
		desc: "ja shirobako Wiki",
		project_name: "SHIROBAKO Wiki",
		url: "http://ja.shirobako.wikia.com/",
		page_url: "http://ja.shirobako.wikia.com/wiki/",
		api_url: "http://ja.shirobako.wikia.com/api.php",
	},
	//		{
	//			name: "Tolkein Gateway",
	//			desc: "Tolkein Gateway",
	//			url: "http://www.tolkiengateway.net",
	//			page_url: "http://www.tolkiengateway.net/wiki/",
	//			api_url: "http://www.tolkiengateway.net/w/api.php",
	//		},
	//		{
	//			name: "日文维基百科",
	//			desc: "日文维基百科",
	//			url: "http://ja.wikipedia.org",
	//			page_url: "http://ja.wikipedia.org/wiki/",
	//			api_url: "http://ja.wikipedia.org/w/api.php",
	//		},
	//  {
	//    name : "",
	//    desc : "",
	//    url : "",
	//    page_url : "",
	//    api_url : "",
	//  },
];